import type { Metadata } from "next";
import { Reveal } from "@/components/motion";
import { SectionHeading } from "@/components/section-heading";
import { certifications, education, principles, profile } from "@/data/portfolio";

export const metadata: Metadata = { title: "About", description: "Professional summary, education, engineering philosophy, and technical interests for Rajith S." };

export default function AboutPage() {
  return <section className="container-pad py-32"><SectionHeading eyebrow="About" title="An engineer who understands systems end-to-end.">Rajith works across software, cloud, networking, AI, and product-facing implementation with a production-first mindset.</SectionHeading><div className="grid gap-6 lg:grid-cols-[.9fr_1.1fr]"><Reveal className="glass rounded-[2rem] p-8"><p className="kicker mb-4">Professional summary</p><p className="copy">Hi, I&apos;m {profile.name}. I build systems that do more than run: they need to scale, survive real-world pressure, and connect intelligent software with reliable infrastructure.</p><p className="copy mt-4">My work spans cloud-native architectures, backend workflows, AI-enhanced features, IoT device streams, and full stack interfaces. The goal is consistent: move complex ideas from prototype to production without losing clarity.</p></Reveal><Reveal delay={0.08} className="glass rounded-[2rem] p-8"><p className="kicker mb-4">Engineering philosophy</p><div className="grid gap-3">{principles.map((p, i) => <div key={p} className="rounded-2xl border border-white/10 bg-black/25 p-4"><span className="font-mono text-xs text-zinc-500">0{i + 1}</span><p className="mt-2 text-zinc-200">{p}</p></div>)}</div></Reveal></div><div className="mt-6 grid gap-6 lg:grid-cols-3"><Reveal className="glass rounded-[2rem] p-6"><p className="kicker mb-4">Education</p>{education.map((e) => <div key={e.school}><h2 className="text-xl font-semibold">{e.degree}</h2><p className="mt-2 text-zinc-400">{e.school}</p><p className="mt-2 text-sm text-zinc-500">{e.period} · {e.detail}</p></div>)}</Reveal><Reveal delay={0.08} className="glass rounded-[2rem] p-6"><p className="kicker mb-4">Technical interests</p><p className="text-zinc-300">Distributed systems, cloud computing, DevOps, networking, AI & machine learning, system design, infrastructure engineering, and full stack development.</p></Reveal><Reveal delay={0.16} className="glass rounded-[2rem] p-6"><p className="kicker mb-4">Certifications</p><ul className="space-y-3 text-zinc-300">{certifications.map((cert) => <li key={cert}>{cert}</li>)}</ul></Reveal></div><Reveal className="mt-6 glass rounded-[2rem] p-8"><p className="kicker mb-4">Career direction</p><p className="copy">Rajith is building toward software engineering roles where cloud architecture, distributed systems, backend reliability, AI integration, and user-facing product quality meet.</p></Reveal></section>;
}
